### ISSUE TITLE
Can't modify config and credentials file on Gitlab-Runner

### ISSUE THREAD

**Issue by GridexX** [bitnami/bitnami-docker-aws-cli#4]
**Problem**
I'm working on the CI/CD pipeline from GitLab. I try to make a job that sync a local folder with a AWS bucket. I'm using the latest version of the image `bitnami/aws-cli:2.2.37`. 

The problem is that i can't edit the config and credentials file from aws-cli inside the script section of the `gitlab-ci.yml` :
```
aws-sync:
  image:
    name: bitnami/aws-cli:2.2.37
    entrypoint: [""]
  stage: build
  variables:
    AWS_ACCESS_KEY_ID: "MY_KEY"
    AWS_SECRET_ACCESS_KEY: "MY_SECRET"
    AWS_DEFAULT_REGION: "fr-par"
    AWS_ENDPOINT: ""
    SYNC_DIR: "."
    AWS_ACL: ""
    ADDITIONAL_OPTIONS: ""
script:
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set plugins.endpoint awscli_plugin_endpoint
    - aws configure set region $AWS_DEFAULT_REGION

```
**Search**
1. The command `aws configure set ...` produces a error : `[Errno 13] Permission denied: '/.aws'`
2. I have tried to look for the file manually the file with `cat ~/.aws/config ` producing the following  `cat: //.aws/config: No such file or directory `. Weird, because as the [AWS's documentation ](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-where)says, credentials and config files should be present inside the ./aws folder
3.  Actually, I'm searching a way to create my own config and credentials files and tell aws to use mine instead of the default one stocked somewhere

If Someone could help me, it would be great :smile:  

**Steps to reproduce the issue:**
1. Create a new repo on GitLab
2. Create a new file ` .gitlab-ci.yml`  inside   
3. Install GitLab-Runner on your PC
4. Copy the current line inside your file : 
```
aws-sync:
  image:
    name: bitnami/aws-cli:2.2.37
    entrypoint: [""]
  stage: build
  variables:
    AWS_ACCESS_KEY_ID: "MY_KEY"
    AWS_SECRET_ACCESS_KEY: "MY_SECRET"
    AWS_DEFAULT_REGION: "fr-par"
    AWS_ENDPOINT: ""
    SYNC_DIR: "."
    AWS_ACL: ""
    ADDITIONAL_OPTIONS: ""
script:
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set plugins.endpoint awscli_plugin_endpoint
    - aws configure set region $AWS_DEFAULT_REGION

```
5. Execute the Pipeline with the command `gitlab-runner exec docker aws-sync`
6. You should have the same error as me

**Additional environment details**
GitLab-Runner : 
```
Version:      14.2.0
Git revision: 58ba2b95
Git branch:   14-2-stable
GO version:   go1.13.8
Built:        2021-08-22T19:47:58+0000
OS/Arch:      linux/amd64
```
Docker Image : `bitnami/aws-cli:2.2.37`
