### ISSUE TITLE
Doesn't Work With IAM Roles For Service Accounts

### ISSUE THREAD

**Issue by hi-artem** [bitnami/bitnami-docker-aws-cli#5]
### Name and Version

public.ecr.aws/bitnami/aws-cli:2.5.3-debian-10-r1

### What steps will reproduce the bug?

Create k8s container and use IAM role for service account. 

The container will have the following envs exported to support IAM role with a web identity provider:
```
AWS_DEFAULT_REGION=us-west-2
AWS_REGION=us-west-2
AWS_ROLE_ARN=arn:aws:iam::xxx:role/XXXX
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

Now run any aws command, for example list s3:

```sh
$ aws s3 ls
[Errno 13] Permission denied: '/.aws'
```

### What is the expected behavior?

Expect this to skip the `~/.aws` file check

### What do you see instead?

It does check the file

**Comment by FraPazGal** [comment]
Hello @hi-artem,

I'm not sure I understand why the expected behaviour should be to skip the `~/.aws` directory. Going by aws-cli's [Configuration settings and precedence](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-precedence) doc, you can pass the configuration by different inputs but the cli will check every one of them right?

Also, it seems strange to me you are getting a permissions error. Did you modify related configuration or are you using the default ocker-compose provided?

**Comment by nielstenboom** [comment]
I am running into the same issue. The issue occurs when using the image in a Kubernetes pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-cli
spec:
  serviceAccountName: "my-openid-serviceaccount"
  containers:
    - name: test
      image: public.ecr.aws/bitnami/aws-cli:2.4.13
      command:
        - /bin/sh
        - '-c'
        - |
          cd /workdir
          date=$(date +%F)
          sleep 3600
```
Where the `my-openid-serviceaccount` has the ` eks.amazonaws.com/role-arn:arn:aws:iam::xxxxxxxxx:role/my-role` annotation

If you create a pod with the above specification on EKS, then shell into it and do `aws s3 ls`, you get the error:
```console 
$ aws s3 ls
[Errno 13] Permission denied: '/.aws'
```
